version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: timeTracking
      POSTGRES_PASSWORD: timeTracking
    volumes:
      - timetracking-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  timetracking-db: {}